#!/usr/bin/env bash
# Groups Apache log data by IP and HTTP code with occurrence counts

awk '{ print $1, $9 }' \
    | sort \
    | uniq -c \
    | sort -nr \
    | awk '{ printf "%8d %s %s\n", $1, $2, $3 }'

