#!/usr/bin/env bash
# Groups Apache log data by IP and HTTP code with occurrence counts

awk '{ count[$1 " " $9]++ }
     END {
         for (key in count)
             print count[key], key
     }' /var/log/apache2/access.log \
     | sort -nr

