#!/usr/bin/env bash
# This is clock
hour=0
while [ $hour -le 12 ]; do
minute=1
echo "Hour: $hour"
     while [ $minute -le 59 ]; do
              echo "$minute"
     minute=$((minute+1))
     done
hour=$((hour+1))
done
